[package]
name = "server"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "net-phys-server"
path = "src/main.rs"

[dependencies]
lib = { path = "../library" }
bevy = { workspace = true }
bevy_quinnet = { workspace = true }
serde = { workspace = true }
