name: Builds

on:
  push:
    branches: ["**"]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    environment:
      name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v24
      - uses: nixbuild/nixbuild-action@v19
        with:
          nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
      - run: nix build \
          --print-build-logs \
          --builders "" \
          --max-jobs 2 \
          --eval-store auto \
          --store ssh-ng://eu.nixbuild.net \
          --accept-flake-config
