name: Windows Builds

on:
  push:
    branches: ['master']

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: 'windows builds'
  cancel-in-progress: true

jobs:
  build-client:
    name: 'Build Windows Client'
    environment:
      name: 'Build Windows Client'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: mycache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Build Client
        run: nix build .#windows-client
      - name: Upload Client
        uses: actions/upload-artifact@v4
        with:
          name: 'client'
          path: './result/bin'
  build-server:
    name: 'Build Windows Server'
    environment:
      name: 'Build Windows Server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: mycache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Build Server
        run: nix build .#windows-server
      - name: Upload Server
        uses: actions/upload-artifact@v4
        with:
          name: 'server'
          path: './result/bin'